import type { Project } from "./types";

// 演示数据：字段与 srs/11-首页与项目导航.md 的数据模型一致，
// 后端项目表建立后由真实 API 替换。
export const mockProjects: Project[] = [
  {
    id: "R2607",
    name: "XX03 探测XX单元鉴定测试",
    nature: "鉴定测试",
    testType: "配置项测试",
    level: "B",
    platform: "CPU",
    organization: "XX研究所",
    owner: "陈俊亦",
    casesTotal: 30,
    casesExecuted: 0,
    openIssues: { critical: 0, serious: 0, normal: 0, suggestion: 0 },
    status: "编制大纲中",
    updatedAt: "2026-06-15",
  },
  {
    id: "R2608",
    name: "XXX 信息处理模块第三方测试",
    nature: "第三方测试",
    testType: "系统测试",
    level: "B",
    platform: "FPGA",
    organization: "XX研究院",
    owner: "李鑫",
    casesTotal: 30,
    casesExecuted: 24,
    openIssues: { critical: 0, serious: 1, normal: 3, suggestion: 2 },
    status: "测试执行中",
    updatedAt: "2026-06-10",
  },
  {
    id: "R2609",
    name: "XX 通信控制软件分析评测",
    nature: "分析评测",
    testType: "配置项测试",
    level: "C",
    platform: "桌面",
    organization: "XX研究所",
    owner: "陈俊亦",
    casesTotal: 25,
    casesExecuted: 18,
    openIssues: { critical: 0, serious: 0, normal: 2, suggestion: 1 },
    status: "大纲已评审",
    updatedAt: "2026-06-05",
  },
  {
    id: "R2610",
    name: "XXX 导航分系统鉴定测试",
    nature: "鉴定测试",
    testType: "系统测试",
    level: "A",
    platform: "CPU",
    organization: "XX研究院",
    owner: "王骏",
    casesTotal: 32,
    casesExecuted: 32,
    openIssues: { critical: 0, serious: 0, normal: 0, suggestion: 1 },
    status: "已完成",
    updatedAt: "2026-05-20",
  },
  {
    id: "R2611",
    name: "XX 雷达信号处理单元改造测试",
    nature: "鉴定测试",
    testType: "配置项测试",
    level: "B",
    platform: "FPGA",
    organization: "XX研究所",
    owner: "李鑫",
    casesTotal: 35,
    casesExecuted: 28,
    openIssues: { critical: 1, serious: 0, normal: 4, suggestion: 0 },
    status: "测试执行中",
    updatedAt: "2026-06-01",
  },
  {
    id: "R2612",
    name: "XXX 数据链软件第三方测试",
    nature: "第三方测试",
    testType: "系统测试",
    level: "C",
    platform: "CPU",
    organization: "XX研究所",
    owner: "赵明",
    casesTotal: 28,
    casesExecuted: 0,
    openIssues: { critical: 0, serious: 0, normal: 0, suggestion: 0 },
    status: "编制大纲中",
    updatedAt: "2026-06-18",
  },
  {
    id: "R2613",
    name: "XX 火控软件分析评测",
    nature: "分析评测",
    testType: "配置项测试",
    level: "D",
    platform: "桌面",
    organization: "XX研究所",
    owner: "陈俊亦",
    casesTotal: 20,
    casesExecuted: 15,
    openIssues: { critical: 0, serious: 0, normal: 1, suggestion: 2 },
    status: "大纲已评审",
    updatedAt: "2026-06-12",
  },
  {
    id: "R2614",
    name: "XXX 电子对抗软件第三方测试",
    nature: "第三方测试",
    testType: "系统测试",
    level: "B",
    platform: "CPU",
    organization: "XX研究院",
    owner: "王骏",
    casesTotal: 30,
    casesExecuted: 22,
    openIssues: { critical: 0, serious: 2, normal: 3, suggestion: 1 },
    status: "测试执行中",
    updatedAt: "2026-05-28",
  },
  {
    id: "R2615",
    name: "XXX 无人机飞控软件鉴定测试",
    nature: "鉴定测试",
    testType: "配置项测试",
    level: "A",
    platform: "FPGA",
    organization: "XX研究所",
    owner: "赵明",
    casesTotal: 25,
    casesExecuted: 0,
    openIssues: { critical: 0, serious: 0, normal: 0, suggestion: 0 },
    status: "编制大纲中",
    updatedAt: "2026-07-01",
  },
  {
    id: "R2616",
    name: "XX 卫星地面站软件第三方测试",
    nature: "第三方测试",
    testType: "系统测试",
    level: "C",
    platform: "桌面",
    organization: "XX研究院",
    owner: "李鑫",
    casesTotal: 30,
    casesExecuted: 30,
    openIssues: { critical: 0, serious: 0, normal: 2, suggestion: 3 },
    status: "已完成",
    updatedAt: "2026-05-15",
  },
  {
    id: "R2617",
    name: "XX 星务计算机软件回归测试",
    nature: "鉴定测试",
    testType: "配置项测试",
    level: "B",
    platform: "CPU",
    organization: "XX研究所",
    owner: "王骏",
    casesTotal: 18,
    casesExecuted: 12,
    openIssues: { critical: 0, serious: 1, normal: 1, suggestion: 0 },
    status: "回归验证中",
    updatedAt: "2026-06-20",
  },
  {
    id: "R2618",
    name: "XXX 综合电子单元软件测评",
    nature: "第三方测试",
    testType: "配置项测试",
    level: "C",
    platform: "FPGA",
    organization: "XX研究院",
    owner: "陈俊亦",
    casesTotal: 26,
    casesExecuted: 26,
    openIssues: { critical: 0, serious: 0, normal: 1, suggestion: 1 },
    status: "报告编制中",
    updatedAt: "2026-06-22",
  },
];
