export type RequirementOrigin = "manual" | "parsed";
export type RequirementStatus = "candidate" | "official" | "excluded" | "superseded";
export type RequirementPrimaryKind =
  | "functional"
  | "interface"
  | "performance"
  | "safety"
  | "reliability"
  | "other";

export interface RequirementSource {
  id: string;
  objectKind: string;
  objectName: string;
  version: string;
  fileType: string;
  originalName: string;
  hasLocalFile: boolean;
  parseState: "ready" | "convert" | "manual" | "register";
}

export interface RequirementSection {
  id: string;
  parentId: string;
  sourceVersionId: string;
  chapterNumber: string;
  title: string;
  origin: RequirementOrigin;
  inScope: boolean;
  sourceAnchor: string;
}

export interface RequirementRecord {
  id: string;
  sourceVersionId: string;
  sectionId: string;
  chapterNumber: string;
  externalIdentifier: string;
  identifierAutoGenerated: boolean;
  name: string;
  description: string;
  primaryKind: RequirementPrimaryKind;
  secondaryKinds: RequirementPrimaryKind[];
  tags: string[];
  origin: RequirementOrigin;
  status: RequirementStatus;
  sourceAnchor: string;
  testItemTaskStatus: "none" | "pending" | "completed";
  deletedFromStatus?: RequirementStatus;
  deletedReason?: string;
  deletedAt?: string;
  updatedAt: string;
  lastModifiedAction?: "create" | "update";
  lastModifiedAt?: string;
  lastModifiedByName?: string;
}

export interface RequirementsWorkbenchSnapshot {
  sources: RequirementSource[];
  sections: RequirementSection[];
  requirements: RequirementRecord[];
}

export interface RequirementIdentifierPreview {
  identifier: string;
  conflictAdjusted: boolean;
}

export interface SaveRequirementPayload {
  sourceVersionId?: string;
  sectionId?: string;
  chapterNumber: string;
  externalIdentifier: string;
  name: string;
  description: string;
  primaryKind: RequirementPrimaryKind;
  secondaryKinds: RequirementPrimaryKind[];
  tags: string[];
}

export interface RequirementStatusPayload {
  ids: string[];
  action: "confirm" | "exclude" | "restore";
  reason?: string;
}

export interface RequirementParseResult {
  sectionCount: number;
  candidateCount: number;
  officialMatchCount: number;
  excludedMatchCount: number;
}

export interface BulkReplacePayload {
  find: string;
  replacement?: string;
  applyToName?: boolean;
  applyToIdentifier?: boolean;
}

export type BulkCreateRequirementItem = {
  nodeType: "requirement";
  chapterNumber: string;
  name: string;
  primaryKind: RequirementPrimaryKind;
};

export interface BulkCreateRequirementPayload {
  sourceVersionId: string;
  items: BulkCreateRequirementItem[];
}

export interface BulkCreateRequirementResult {
  requirementCount: number;
}

export interface BulkUpdateRequirementPayload {
  ids: string[];
  primaryKind?: RequirementPrimaryKind;
  secondaryKinds?: RequirementPrimaryKind[];
  replace?: BulkReplacePayload;
}

export interface BulkPurgeRequirementsPayload {
  ids?: string[];
  all?: boolean;
  reason: string;
}

export interface RequirementEvent {
  id: string;
  action: "create" | "update" | "confirm" | "exclude" | "restore" | "parse";
  fromStatus: RequirementStatus | "";
  toStatus: RequirementStatus | "";
  detail: string;
  operatedBy: string;
  operatedByName: string;
  operatedAt: string;
}
