export type RequirementOrigin = "manual" | "parsed";
export type RequirementStatus = "candidate" | "official" | "excluded" | "superseded";
export type RequirementPrimaryKind =
  | "functional"
  | "interface"
  | "performance"
  | "safety"
  | "reliability"
  | "other";

export interface RequirementSource {
  id: string;
  objectKind: string;
  objectName: string;
  version: string;
  fileType: string;
  originalName: string;
  hasLocalFile: boolean;
  parseState: "ready" | "convert" | "manual" | "register";
}

export interface RequirementSection {
  id: string;
  parentId: string;
  sourceVersionId: string;
  chapterNumber: string;
  title: string;
  origin: RequirementOrigin;
  inScope: boolean;
  sourceAnchor: string;
}

export interface RequirementRecord {
  id: string;
  sourceVersionId: string;
  sectionId: string;
  chapterNumber: string;
  externalIdentifier: string;
  identifierAutoGenerated: boolean;
  name: string;
  description?: string;
  descriptionExcerpt: string;
  hasDescription: boolean;
  primaryKind: RequirementPrimaryKind;
  secondaryKinds: RequirementPrimaryKind[];
  tags: string[];
  origin: RequirementOrigin;
  status: RequirementStatus;
  sourceAnchor: string;
  testItemTaskStatus: "none" | "pending" | "completed";
  deletedFromStatus?: RequirementStatus;
  deletedReason?: string;
  deletedAt?: string;
  updatedAt: string;
  lastModifiedAction?: "create" | "update";
  lastModifiedAt?: string;
  lastModifiedByName?: string;
}

export interface RequirementsWorkbenchSnapshot {
  sources: RequirementSource[];
  sections: RequirementSection[];
  requirements: RequirementRecord[];
}

export interface RequirementContent {
  id: string;
  description: string;
  hasDescription: boolean;
  updatedAt: string;
}

export type RequirementSearchField =
  | "chapter"
  | "description"
  | "externalIdentifier"
  | "name"
  | "tags";

export interface RequirementSearchHit {
  id: string;
  fields: RequirementSearchField[];
  excerpt: string;
}

export interface RequirementSearchResult {
  items: RequirementSearchHit[];
  total: number;
}

export interface RequirementIdentifierPreview {
  identifier: string;
  conflictAdjusted: boolean;
}

export interface SaveRequirementPayload {
  sourceVersionId?: string;
  sectionId?: string;
  chapterNumber: string;
  externalIdentifier: string;
  name: string;
  description: string;
  primaryKind: RequirementPrimaryKind;
  secondaryKinds: RequirementPrimaryKind[];
  tags: string[];
}

export interface RequirementStatusPayload {
  ids: string[];
  action: "confirm" | "exclude" | "restore";
  reason?: string;
}

export interface RequirementParseResult {
  sectionCount: number;
  candidateCount: number;
  officialMatchCount: number;
  excludedMatchCount: number;
  /** 解析时为需求构建的正文块数量（外部文档引擎可用时）。 */
  bodyBlockCount: number;
  /** 外部文档引擎不可用时为 true，正文降级为纯文本。 */
  bodyBuildSkipped: boolean;
  bodyBuildError?: string;
}

export interface BulkReplacePayload {
  find: string;
  replacement?: string;
  applyToName?: boolean;
  applyToIdentifier?: boolean;
}

export type BulkCreateRequirementItem = {
  nodeType: "requirement";
  chapterNumber: string;
  name: string;
  primaryKind: RequirementPrimaryKind;
};

export interface BulkCreateRequirementPayload {
  sourceVersionId: string;
  items: BulkCreateRequirementItem[];
}

export interface BulkCreateRequirementResult {
  requirementCount: number;
}

export interface BulkUpdateRequirementPayload {
  ids: string[];
  primaryKind?: RequirementPrimaryKind;
  secondaryKinds?: RequirementPrimaryKind[];
  replace?: BulkReplacePayload;
}

export interface BulkPurgeRequirementsPayload {
  ids?: string[];
  all?: boolean;
  reason: string;
}
export interface BulkCleanNamesPayload {
  ids: string[];
}

export interface BulkCleanNamesResult {
  updatedCount: number;
}

export interface RequirementEvent {
  id: string;
  action: "create" | "update" | "confirm" | "exclude" | "restore" | "parse";
  fromStatus: RequirementStatus | "";
  toStatus: RequirementStatus | "";
  detail: string;
  operatedBy: string;
  operatedByName: string;
  operatedAt: string;
}

export type RequirementBlockNodeType =
  | "doc"
  | "paragraph"
  | "text"
  | "heading"
  | "bulletList"
  | "orderedList"
  | "listItem"
  | "table"
  | "tableRow"
  | "tableHeader"
  | "tableCell"
  | "assetImage"
  | "pagebreak";

export interface RequirementBlockMark {
  type: "bold" | "italic" | "underline";
  attrs?: Record<string, unknown>;
}

export interface RequirementBlockNode {
  type: RequirementBlockNodeType;
  attrs?: Record<string, unknown>;
  content?: RequirementBlockNode[];
  text?: string;
  marks?: RequirementBlockMark[];
}

export interface RequirementBodyResponse {
  requirementId: string;
  doc: RequirementBlockNode;
  plainText: string;
  origin: "manual" | "auto_draft" | "imported";
  authoringMode: "auto" | "manual" | "mixed";
  hasContent: boolean;
  updatedAt: string;
}

export interface RequirementAsset {
  id: string;
  mimeType: string;
  width: number;
  height: number;
  fileSize: number;
}
